version: "3.4"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transporter
    ports:
      - 3306:3306
    restart: unless-stopped
  api:
    image: transporter-api
    working_dir: /apps/transporter
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app/transporter
    depends_on:
      - db